// cms-donate.js — single source of truth for the LDAH donate URL.
//
// On every page load, fetches system/donateBlocks.donateUrl from Firestore
// and rewrites every PayPal donate touchpoint on the page so changes made
// in CMS take effect everywhere without code edits.
//
// Handles two patterns:
//   1. <a href="https://www.paypal.com/donate?hosted_button_id=...">
//   2. <form action="https://www.paypal.com/donate">
//        <input type="hidden" name="hosted_button_id" value="...">
//
// Also watches the DOM so late-injected fragments (header.html, footer.html
// loaded by fetch+innerHTML on most pages) get rewritten when they appear.
//
// To CHANGE THE DONATE URL itself, do NOT edit this file or any HTML.
// Go to LDAH-Int → Admin → List Management → Donate Block — Universal → Donate URL.
//
// Fallback: if Firestore is slow or unreachable the page keeps the hardcoded
// values that are already in the HTML, so donate links always work.

(function () {
  var cachedUrl = null;
  var cachedHostedButtonId = null;

  function firebaseReady() {
    return typeof firebase !== "undefined" && firebase.apps && firebase.apps.length > 0;
  }

  function extractHostedButtonId(url) {
    try {
      var q = url.split("?")[1] || "";
      var pairs = q.split("&");
      for (var i = 0; i < pairs.length; i++) {
        var kv = pairs[i].split("=");
        if (kv[0] === "hosted_button_id") return decodeURIComponent(kv[1] || "");
      }
    } catch (e) {}
    return null;
  }

  function applyTo(root) {
    if (!cachedUrl || !root || !root.querySelectorAll) return;
    // Anchor-based donate buttons
    root.querySelectorAll('a[href*="paypal.com/donate?hosted_button_id="]').forEach(function (a) {
      a.setAttribute("href", cachedUrl);
    });
    // Form-based donate buttons (hidden hosted_button_id input)
    if (cachedHostedButtonId) {
      root.querySelectorAll('form[action*="paypal.com/donate"] input[name="hosted_button_id"]').forEach(function (input) {
        input.setAttribute("value", cachedHostedButtonId);
        // Also keep the .value property in sync for any code that reads it
        try { input.value = cachedHostedButtonId; } catch (e) {}
      });
    }
  }

  function watchDom() {
    if (typeof MutationObserver === "undefined" || !document.body) return;
    var obs = new MutationObserver(function (mutations) {
      for (var i = 0; i < mutations.length; i++) {
        var added = mutations[i].addedNodes;
        for (var j = 0; j < added.length; j++) {
          var n = added[j];
          if (n && n.nodeType === 1) applyTo(n);
        }
      }
    });
    obs.observe(document.body, { childList: true, subtree: true });
  }

  function loadAndApply() {
    try {
      firebase.firestore().collection("system").doc("donateBlocks").get()
        .then(function (snap) {
          if (!snap || !snap.exists) return;
          var data = snap.data();
          if (!data || typeof data.donateUrl !== "string" || !data.donateUrl) return;
          cachedUrl = data.donateUrl;
          cachedHostedButtonId = extractHostedButtonId(cachedUrl);
          applyTo(document);   // current DOM
          watchDom();          // future DOM (header/footer fragments etc.)
        })
        .catch(function () { /* silent — hardcoded fallback stands */ });
    } catch (e) { /* silent — hardcoded fallback stands */ }
  }

  function start() {
    if (firebaseReady()) { loadAndApply(); return; }
    // The host page may init Firebase a few ms after this script runs.
    var tries = 0;
    var iv = setInterval(function () {
      if (firebaseReady() || tries++ > 40) {
        clearInterval(iv);
        if (firebaseReady()) loadAndApply();
      }
    }, 50);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", start);
  } else {
    start();
  }
})();
